Replacement PR to avoid merge problems
ACDguide/BigData pull request #27
Opened 2021-11-19 04:55 UTC by hot007

Re-issuing PR on a new branch so Paola can better untangle our duplicate edits to the tools page. 
If approved, we'll merge my changes here and delete the other PR.

resolves #15 , resolves #16 , resolves #23

Addresses #24

replaces #25

2021-11-19 06:00 UTC, paolap commented
It's fine by me, I've merged this into the branch I was working on the tools section and integrated Claire changes with mine.

2021-11-19 06:04 UTC, paolap approved these changes

2021-11-19 07:17 UTC, paigem requested changes
This PR is really great!! A leap forward in the content of this book. Thanks to all who contributed to this.

I just have a couple comments, and found several minor typos, which is why I am requesting changes before merging.

2021-11-19 07:17 UTC, paigem commented on BigData/format_metadata.md
> +Data which is expected to be used for timeseries analysis most often should be stored with chunks like e.g. `(744, 1, 1)`, so that each disk read extracts a lot of time steps at each point location.
I think it might be more clear to specify the arrays dimension names at the start of this line, e.g. ('time','lat','lon'), in order to interpret the example chunk sizes provided here. For example, the first sentence could read "Data with dimensions `('time','lat','lon')` that is expected to be used for timeseries..."

2021-11-19 07:17 UTC, paigem commented on BigData/different_tools.md
> +Other languages and tools exist which can work with netCDF data (e.g. C, FORTRAN, ArcGIS, QGIS, paraview, panoply, Ferret, as well as the deprecated NCL), but on this page we focus on tools commonly
Typo: "typically"

2021-11-19 07:17 UTC, paigem commented on BigData/different_tools.md
> +As a licensed tool MATLAB might not be available to other researchers and collaborators, so even if you are producing data with Matlab, it is best to avoid saving the data as `.mat` files, use the be
Typo: add "and" between "...files, AND use the best alternative..."

2021-11-19 07:17 UTC, paigem commented on BigData/different_tools.md
> +CDO is useful to calculate climatologies, regrid datasets, select subset both spatially and temporally. It can be used to perform simple transformations across an entire variable as for NCO. It is us
Typos: 
- "...regrid datasets, AND select subsetS both spatially..."
- "...time axis operations, SUCH as..."

2021-11-19 07:17 UTC, paigem commented on BigData/format_metadata.md
> +Not all file formats support unlimited dimensions, and conversely netCDF4 supports exactly one unlimited dimension (the underlying HDF5 format supports multiple unlimited dimensions). Zarr does not s
It might be nice to describe what it means to have an "unlimited" dimension. Perhaps I missed the description elsewhere, but I'm actually not entirely sure what that means and why a dataset would have such a dimension...

2021-11-22 00:29 UTC, hot007 commented on BigData/format_metadata.md
> +Even if a calendar are units are clearly defined, not all datetime libraries are capable of dealing with dates far in the past or future. In this case it may be necessary to explicitly use "CFtime" w
done

2021-11-22 00:30 UTC, hot007 commented on BigData/format_metadata.md
> +Some datasets, for example those derived from observations, may differentiate between NaN values, and missing values. Sometimes the value `0` is recorded for "no data" which can cause problems for va
done

2021-11-22 00:31 UTC, hot007 commented on BigData/format_metadata.md
> +Ocean models are often run on a tripolar grid to avoid the existence of a singularity at the North Pole. Instead a global grid is constructed with 3 poles all under conintenal land masses to permit n
ooh that was a funny one! done.

2021-11-22 00:31 UTC, hot007 commented on BigData/format_metadata.md
> +Some models use mesh grids which conform to coastlines to permit higher resolution in areas of particular interest without needing to run the whole model at high resolution. In this case the `UGRID`
done

2021-11-22 00:33 UTC, hot007 commented on BigData/format_metadata.md
> +While a typical climate model using cartesian coordinates will usually have both dimensions and variables of "latitude" and "longitude", for other grid types it is typically to have other dimensions
done, and removed first 'typical' from the sentence to avoid repetition.

2021-11-22 00:34 UTC, hot007 commented on BigData/format_metadata.md
> +NetCDF has long supported using scale factors and offsets to reduce required precision in data storage, ie, enable reducing required disk space. These capabilities are rarely used these days, but som
done

2021-11-22 00:38 UTC, hot007 commented on BigData/format_metadata.md
> +Data which is expected to be used for timeseries analysis most often should be stored with chunks like e.g. `(744, 1, 1)`, so that each disk read extracts a lot of time steps at each point location.
good suggestion

2021-11-22 00:39 UTC, hot007 commented on BigData/different_tools.md
> +Other languages and tools exist which can work with netCDF data (e.g. C, FORTRAN, ArcGIS, QGIS, paraview, panoply, Ferret, as well as the deprecated NCL), but on this page we focus on tools commonly
thank heavens for you proof reading these!!

2021-11-22 00:40 UTC, hot007 commented on BigData/different_tools.md
> +As a licensed tool MATLAB might not be available to other researchers and collaborators, so even if you are producing data with Matlab, it is best to avoid saving the data as `.mat` files, use the be
done

2021-11-22 00:41 UTC, hot007 commented on BigData/different_tools.md
> +CDO is useful to calculate climatologies, regrid datasets, select subset both spatially and temporally. It can be used to perform simple transformations across an entire variable as for NCO. It is us
done

2021-11-22 00:50 UTC, hot007 commented on BigData/format_metadata.md
> +Not all file formats support unlimited dimensions, and conversely netCDF4 supports exactly one unlimited dimension (the underlying HDF5 format supports multiple unlimited dimensions). Zarr does not s
Expanded to explain, with link given to the nc-zarr test page where this is an issue.

2021-11-22 00:51 UTC, hot007 commented
Don't need @chloemackallah 's review here as she reviewed on the other PR

2021-11-22 00:58 UTC, hot007 commented
How's that now @paigem ?

2021-11-22 01:13 UTC, paigem approved these changes
Looks great @hot007! Thanks again for adding all of this - what a great improvement to the ACDG!

2021-11-22 01:16 UTC, paigem commented on BigData/different_tools.md
> +Other languages and tools exist which can work with netCDF data (e.g. C, FORTRAN, ArcGIS, QGIS, paraview, panoply, Ferret, as well as the deprecated NCL), but on this page we focus on tools commonly
You've done the hard part here of adding so much new content! All of these are just minor corrections - everything you wrote was very understandable! I was just being a bit nit-picky. 🙂

2021-11-22 01:16 UTC, paigem commented
Looks like we are just waiting on @AliciaTak's review before merging!

2021-11-22 02:47 UTC, paolap commented
> Looks like we are just waiting on @AliciaTak's review before merging!

I've integrated Claire's changes for the different_tools file (which I believe is the reason Alicia was requested to review) into my branch, where I was already making changes to that part, so Alicia should have a chance to review all of them together then

2021-11-23 00:39 UTC, merged