Update where to get help page including link to CLEX ...
ACDguide/BigData pull request #37
Opened 2022-01-13 02:56 UTC by hot007

how to ask for help page.

@paigem please review.

Should again resolve #9

2022-01-13 03:25 UTC, paigem requested changes

2022-01-13 03:25 UTC, paigem commented on BigData/help.md
> +**DO NOT BE AFRAID TO ASK FOR HELP!** It is normal to get stuck sometimes and we have all been there, either learning a new tool, or struggling with something we feel like we should be able to do but
Love this. 🙂

2022-01-13 03:25 UTC, paigem commented on BigData/help.md
> +CLEX have compiled [this excellent guide](http://climate-cms.wikis.unsw.edu.au/Getting_Help) for how to write help requests.
I wonder if we should stress this a bit more? E.g., if someone is at all involved in CLEX (or maybe that's not even a pre-requisite? We should make this clear in our book.), then this should definitely be their number one go-to for where to get help and how to ask for it. 

Perhaps we can highlight it at the top of the page or put it in bold?

2022-01-13 03:25 UTC, paigem commented on BigData/help.md
>  | CSC Data Science Network | Community of data scientists in CSIRO's climate science centre | CSIRO MS Teams group - request membership from Chloe Mackallah or Claire Trenham |
Is the CSC Data Science Network just for CSIRO folks? If so, let's make that clear. If not, can we link to emails or sites where people could find emails for Chloe or Claire?

2022-01-13 05:05 UTC, hot007 commented on BigData/help.md
> +CLEX have compiled [this excellent guide](http://climate-cms.wikis.unsw.edu.au/Getting_Help) for how to write help requests.
Good idea, change made. I've realised I'm bad at PRs and it's all coming in the same one but now added here.

2022-01-13 05:07 UTC, hot007 commented on BigData/help.md
>  | CSC Data Science Network | Community of data scientists in CSIRO's climate science centre | CSIRO MS Teams group - request membership from Chloe Mackallah or Claire Trenham |
Changed description to clarify it's a CSIRO thing, but not providing actual emails for bots reasons - I figure knowing our names makes us easy enough to find internally.

2022-01-13 05:09 UTC, hot007 commented
I am bad at PRs and didn't realise I couldn't just open a new one for the changes I made to the platforms page so that's here too... please review @ScottWales and @paigem . Links to #36 .
In particular, @ScottWales  please critically review the institutional resources page as well as NCI descriptions, and @paigem please fix Pangeo to be actually correct and relevant!

2022-01-13 05:10 UTC, hot007 commented on BigData/help.md
> +CLEX have compiled [this excellent guide](http://climate-cms.wikis.unsw.edu.au/Getting_Help) for how to write help requests.
Resovled by commit 5f6a86a

2022-01-13 05:10 UTC, hot007 commented on BigData/help.md
>  | CSC Data Science Network | Community of data scientists in CSIRO's climate science centre | CSIRO MS Teams group - request membership from Chloe Mackallah or Claire Trenham |
resolved by commit f809078

2022-01-13 06:32 UTC, paigem requested changes
Looks great @hot007! I added a lot of content to the Pangeo section. I used the "suggestion" tool for the first time (and almost by accident as I tried to figure out what the icon meant...) - hopefully that makes it easy to add the markdown code directly?

2022-01-13 06:32 UTC, paigem commented on BigData/platforms.md
> +For more information, see ??? join the Pangeo Oceania community ??
```suggestion
For more information, see the [Pangeo website](https://pangeo.io/index.html). To get involved in the community, you can post on the [Pangeo Discourse Forum](https://discourse.pangeo.io) or attend [Pangeo community meetings](https://pangeo.io/meeting-notes.html). The Pangeo Oceania group meets monthly at Australian-friendly times: 3rd Friday of the month at 1pm Australian Eastern Time. All are welcome and meeting agendas and connection details are posted [here](https://discourse.pangeo.io/t/pangeo-oceania-meetings-and-agendas/1762).

```

2022-01-13 06:32 UTC, paigem commented on BigData/platforms.md
> +Pangeo as a paradigm, all the time. The pangeo cloud infrastructure though??
```suggestion
If you use any of the tools like `xarray` or `dask`, then you are already "using" Pangeo. 

Pangeo Cloud can be used for any Earth-related research you undertake. It would be especially useful if you want to analyze across many datasets that are already stored in the Pangeo Cloud. Additionally, as a cloud computing service, it allows users to scale up computations very easily and on-demand, making it especially useful for data analysis on very large datasets. Pangeo Cloud is not currently optimized for running models, but rather for data analysis.

```

2022-01-13 06:32 UTC, paigem commented on BigData/platforms.md
> +
```suggestion

Anyone can request access to Pangeo Cloud on the [Pangeo Cloud documentation site](https://pangeo.io/cloud.html), under "Sign Up". This will take you to a Google form where you can fill in details of the research you would like to use Pangeo Cloud for, and after submission you should hear back within a few days if your request was approved. At this time, most projects related to climate and geoscience get approved. The link above also contains other pertinent information to using Pangeo Cloud.

*Note that the Pangeo Cloud is currently being run with limited funds, and should therefore not be used as a reliable computing platform for long-term projects, as funding could run out at any time. However, if you have funding and are able to pay for cloud computing resources, you can request your own Pangeo-like cloud environment from [2i2c](https://2i2c.org) - the same company that runs and maintains the Pangeo Cloud.*
```

2022-01-14 00:15 UTC, ScottWales approved these changes
Looks good Claire

2022-01-14 00:15 UTC, ScottWales commented on BigData/platforms.md
> +The datasets hosted on NCI maybe centrally managed, e.g. by NCI (CMIP, ERA5) or the community (precipitation data, other reanalyses). An interface to help researchers idenitfy what climate data is av
Yeah maybe omit and open a ticket to re-add once invenio is ready

2022-01-14 00:15 UTC, ScottWales commented on BigData/platforms.md
> +Many universities support internal HPCs on a much smaller scale than NCI and Pawsey, but that are often beneficial at a research group level. UTas (TPAC), UniMelb (Spartan), and UNSW (??) all have sy
UNSW system appears to be 'Katana'. Also maybe note that using a local system limits collaboration and the number of people who are able to help if you run into problems, while there is a large community at NCI

2022-01-14 02:55 UTC, hot007 commented on BigData/platforms.md
> +Many universities support internal HPCs on a much smaller scale than NCI and Pawsey, but that are often beneficial at a research group level. UTas (TPAC), UniMelb (Spartan), and UNSW (??) all have sy
Thanks and good point, have added a note under Gadi about both help@nci as well as cws-help.

2022-01-14 03:07 UTC, hot007 commented on BigData/platforms.md
> +The datasets hosted on NCI maybe centrally managed, e.g. by NCI (CMIP, ERA5) or the community (precipitation data, other reanalyses). An interface to help researchers idenitfy what climate data is av
resolved by 8118581

2022-01-14 03:08 UTC, hot007 commented on BigData/platforms.md
> +The "OOD" or "VDI" is ideal for exploratory and interactive work such as code development, data exploration and visualistaion, and tasks requiring internet access (e.g. working with data from externa
resolved by 8118581

2022-01-14 03:10 UTC, hot007 commented on BigData/platforms.md
> +Pangeo is a community built aroudn analysis of large scale Earth systems data. Pangeo recommend use of python tools like jupyter, xarray and dask. Pangeo supports collections of selected datasets pub
This would have worked beautifully as I can simply add these commits to the PR directly. Unfortunately because it's not merged yet it doesn't sync back up to my fork so my other edits overrode them :( I think it would have worked if I did it in the other order - my edits then merge your suggestions. Still learning how to do this... for now I've re-added them manually.

2022-01-14 03:10 UTC, hot007 commented on BigData/platforms.md
> +Many universities support internal HPCs on a much smaller scale than NCI and Pawsey, but that are often beneficial at a research group level. UTas (TPAC), UniMelb (Spartan), and UNSW (??) all have sy
resolved by 8118581

2022-01-14 03:12 UTC, hot007 commented
Okay, I messed it up because I could commit @paigem 's suggestions directly to the PR but my other edits blatted them again, needed to do my "remote" (fork) edits first. Lesson learned I hope! Anyway I think it's good to merge now @paigem ?

Thanks very much both for your feedback!

2022-03-09 00:23 UTC, paigem commented
Sorry for letting this sit on the wayside for so long @hot007 - this looks great and I'll merge now!

2022-03-09 00:23 UTC, merged